/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/abstractFlow.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="abstractFlow"
        geometry={nodes.abstractFlow.geometry}
        material={materials.orgMaterial}
        morphTargetDictionary={nodes.abstractFlow.morphTargetDictionary}
        morphTargetInfluences={nodes.abstractFlow.morphTargetInfluences}
      />
    </group>
  )
}

useGLTF.preload('/abstractFlow.glb')
