/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { useFrame } from 'react-three-fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ShapeKeys.glb')

  // Set up state for the hovered and active state
  // const [hovered, setHover] = useState(false)



  useFrame(() => {
    group.current.rotation.x = group.current.rotation.y += 0.01
  })

  return (


    
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.SVGMat}
        geometry={nodes.Åskvåg_Logo.geometry}
        position={[0, 0, 0]}
        scale={[5.35, 5.35, 5.35]}

        // onPointerOver={(event) => setHover(true)}
        // onPointerOut={(event) => setHover(false)}
        >
      <meshStandardMaterial color={'white'} /></mesh>
    </group>
  )
}

// useGLTF.preload('/askvagaLogoCmp.glb')
