/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
	const group = useRef()
	const { nodes, materials } = useGLTF('/ShapeKeys.glb')

	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				name='Cube'
				geometry={nodes.Cube.geometry}
				material={materials.Material}
				morphTargetDictionary={nodes.Cube.morphTargetDictionary}
				morphTargetInfluences={nodes.Cube.morphTargetInfluences}
			/>
		</group>
	)
}

useGLTF.preload('/ShapeKeys.glb')
